// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tenvis.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Statement_Type int32

const (
	Statement_NOMINATE    Statement_Type = 0
	Statement_PREPARE     Statement_Type = 1
	Statement_COMMIT      Statement_Type = 2
	Statement_EXTERNALIZE Statement_Type = 3
)

var Statement_Type_name = map[int32]string{
	0: "NOMINATE",
	1: "PREPARE",
	2: "COMMIT",
	3: "EXTERNALIZE",
}

var Statement_Type_value = map[string]int32{
	"NOMINATE":    0,
	"PREPARE":     1,
	"COMMIT":      2,
	"EXTERNALIZE": 3,
}

func (x Statement_Type) String() string {
	return proto.EnumName(Statement_Type_name, int32(x))
}

func (Statement_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{2, 0}
}

type StreamingRequest struct {
	Test                 string   `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{0}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

type Message struct {
	NodeID               string       `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Nominate             *Nominate    `protobuf:"bytes,2,opt,name=nominate,proto3" json:"nominate,omitempty"`
	Prepare              *Prepare     `protobuf:"bytes,3,opt,name=prepare,proto3" json:"prepare,omitempty"`
	Commit               *Commit      `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Externalize          *Externalize `protobuf:"bytes,5,opt,name=externalize,proto3" json:"externalize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *Message) GetNominate() *Nominate {
	if m != nil {
		return m.Nominate
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if m != nil {
		return m.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *Message) GetExternalize() *Externalize {
	if m != nil {
		return m.Externalize
	}
	return nil
}

type Statement struct {
	Type                 Statement_Type `protobuf:"varint,2,opt,name=type,proto3,enum=network.Statement_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{2}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetType() Statement_Type {
	if m != nil {
		return m.Type
	}
	return Statement_NOMINATE
}

type Nominate struct {
	Voted                []*Value `protobuf:"bytes,1,rep,name=voted,proto3" json:"voted,omitempty"`
	Accepted             []*Value `protobuf:"bytes,2,rep,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nominate) Reset()         { *m = Nominate{} }
func (m *Nominate) String() string { return proto.CompactTextString(m) }
func (*Nominate) ProtoMessage()    {}
func (*Nominate) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{3}
}

func (m *Nominate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nominate.Unmarshal(m, b)
}
func (m *Nominate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nominate.Marshal(b, m, deterministic)
}
func (m *Nominate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nominate.Merge(m, src)
}
func (m *Nominate) XXX_Size() int {
	return xxx_messageInfo_Nominate.Size(m)
}
func (m *Nominate) XXX_DiscardUnknown() {
	xxx_messageInfo_Nominate.DiscardUnknown(m)
}

var xxx_messageInfo_Nominate proto.InternalMessageInfo

func (m *Nominate) GetVoted() []*Value {
	if m != nil {
		return m.Voted
	}
	return nil
}

func (m *Nominate) GetAccepted() []*Value {
	if m != nil {
		return m.Accepted
	}
	return nil
}

type Prepare struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{4}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

type Commit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{5}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

type Externalize struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Externalize) Reset()         { *m = Externalize{} }
func (m *Externalize) String() string { return proto.CompactTextString(m) }
func (*Externalize) ProtoMessage()    {}
func (*Externalize) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{6}
}

func (m *Externalize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Externalize.Unmarshal(m, b)
}
func (m *Externalize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Externalize.Marshal(b, m, deterministic)
}
func (m *Externalize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Externalize.Merge(m, src)
}
func (m *Externalize) XXX_Size() int {
	return xxx_messageInfo_Externalize.Size(m)
}
func (m *Externalize) XXX_DiscardUnknown() {
	xxx_messageInfo_Externalize.DiscardUnknown(m)
}

var xxx_messageInfo_Externalize proto.InternalMessageInfo

type Value struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{7}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Slot struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Values               []*Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa8cb0daccce723, []int{8}
}

func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (m *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(m, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Slot) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("network.Statement_Type", Statement_Type_name, Statement_Type_value)
	proto.RegisterType((*StreamingRequest)(nil), "network.StreamingRequest")
	proto.RegisterType((*Message)(nil), "network.Message")
	proto.RegisterType((*Statement)(nil), "network.Statement")
	proto.RegisterType((*Nominate)(nil), "network.Nominate")
	proto.RegisterType((*Prepare)(nil), "network.Prepare")
	proto.RegisterType((*Commit)(nil), "network.Commit")
	proto.RegisterType((*Externalize)(nil), "network.Externalize")
	proto.RegisterType((*Value)(nil), "network.Value")
	proto.RegisterType((*Slot)(nil), "network.Slot")
}

func init() { proto.RegisterFile("tenvis.proto", fileDescriptor_dfa8cb0daccce723) }

var fileDescriptor_dfa8cb0daccce723 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x8b, 0xd3, 0x50,
	0x10, 0xc5, 0x4d, 0x9b, 0xa6, 0xe9, 0xa4, 0xee, 0xc6, 0x61, 0xd1, 0xa8, 0x2f, 0xe5, 0x22, 0x6b,
	0x59, 0xb1, 0x48, 0x05, 0x1f, 0x7c, 0x10, 0xca, 0x36, 0x0f, 0x05, 0x9b, 0x2d, 0xb7, 0x41, 0x44,
	0x7c, 0xb9, 0xb6, 0xc3, 0x12, 0x6c, 0xfe, 0x98, 0xcc, 0xd6, 0xae, 0xdf, 0xd5, 0xef, 0x22, 0xb9,
	0xb9, 0x9b, 0xad, 0xa0, 0x6f, 0x77, 0xe6, 0xfc, 0x86, 0x49, 0xce, 0x1c, 0x18, 0x32, 0x65, 0xfb,
	0xa4, 0x9a, 0x14, 0x65, 0xce, 0x39, 0xf6, 0x33, 0xe2, 0x9f, 0x79, 0xf9, 0x5d, 0x9c, 0x83, 0xbf,
	0xe6, 0x92, 0x54, 0x9a, 0x64, 0xd7, 0x92, 0x7e, 0xdc, 0x50, 0xc5, 0x88, 0x60, 0x33, 0x55, 0x1c,
	0x58, 0x23, 0x6b, 0x3c, 0x90, 0xfa, 0x2d, 0x7e, 0x5b, 0xd0, 0x5f, 0x52, 0x55, 0xa9, 0x6b, 0xc2,
	0xc7, 0xe0, 0x44, 0xf9, 0x96, 0x16, 0x73, 0x43, 0x98, 0x0a, 0x5f, 0x83, 0x9b, 0xe5, 0x69, 0x92,
	0x29, 0xa6, 0xa0, 0x33, 0xb2, 0xc6, 0xde, 0xf4, 0xd1, 0xc4, 0xec, 0x99, 0x44, 0x46, 0x90, 0x2d,
	0x82, 0x17, 0xd0, 0x2f, 0x4a, 0x2a, 0x54, 0x49, 0x41, 0x57, 0xd3, 0x7e, 0x4b, 0xaf, 0x9a, 0xbe,
	0xbc, 0x03, 0xf0, 0x25, 0x38, 0x9b, 0x3c, 0x4d, 0x13, 0x0e, 0x6c, 0x8d, 0x9e, 0xb6, 0xe8, 0xa5,
	0x6e, 0x4b, 0x23, 0xe3, 0x3b, 0xf0, 0xe8, 0xc0, 0x54, 0x66, 0x6a, 0x97, 0xfc, 0xa2, 0xa0, 0xa7,
	0xe9, 0xb3, 0x96, 0x0e, 0xef, 0x35, 0x79, 0x0c, 0x8a, 0x03, 0x0c, 0xd6, 0xac, 0x98, 0x52, 0xca,
	0x18, 0x5f, 0x81, 0xcd, 0xb7, 0x45, 0xf3, 0x13, 0x27, 0xd3, 0x27, 0xed, 0x74, 0x4b, 0x4c, 0xe2,
	0xdb, 0x82, 0xa4, 0x86, 0xc4, 0x07, 0xb0, 0xeb, 0x0a, 0x87, 0xe0, 0x46, 0x57, 0xcb, 0x45, 0x34,
	0x8b, 0x43, 0xff, 0x01, 0x7a, 0xd0, 0x5f, 0xc9, 0x70, 0x35, 0x93, 0xa1, 0x6f, 0x21, 0x80, 0x73,
	0x79, 0xb5, 0x5c, 0x2e, 0x62, 0xbf, 0x83, 0xa7, 0xe0, 0x85, 0x9f, 0xe3, 0x50, 0x46, 0xb3, 0x8f,
	0x8b, 0x2f, 0xa1, 0xdf, 0x15, 0x5f, 0xc1, 0xbd, 0x33, 0x07, 0x5f, 0x40, 0x6f, 0x9f, 0x33, 0x6d,
	0x03, 0x6b, 0xd4, 0x1d, 0x7b, 0xd3, 0x93, 0x76, 0xf3, 0x27, 0xb5, 0xbb, 0x21, 0xd9, 0x88, 0x78,
	0x01, 0xae, 0xda, 0x6c, 0xa8, 0xa8, 0xc1, 0xce, 0x3f, 0xc1, 0x56, 0x17, 0x03, 0xe8, 0x1b, 0x33,
	0x85, 0x0b, 0x4e, 0x63, 0x96, 0x78, 0x08, 0xde, 0x91, 0x11, 0xe2, 0x39, 0xf4, 0xf4, 0x58, 0x7d,
	0xf8, 0xad, 0x62, 0xa5, 0xcf, 0x3a, 0x94, 0xfa, 0x2d, 0xe6, 0x60, 0xaf, 0x77, 0x39, 0xe3, 0x19,
	0xf4, 0x92, 0x6c, 0x4b, 0x07, 0x2d, 0xda, 0xb2, 0x29, 0xf0, 0x1c, 0x9c, 0x7d, 0x3d, 0x5a, 0xfd,
	0xe7, 0x43, 0x8c, 0x3a, 0x9d, 0x83, 0x13, 0xeb, 0xfc, 0xe1, 0xfb, 0xda, 0x68, 0x13, 0x38, 0x7c,
	0x7a, 0x64, 0xed, 0xdf, 0x21, 0x7c, 0x76, 0x1f, 0x06, 0x13, 0xbb, 0x37, 0xd6, 0x37, 0x47, 0x87,
	0xf7, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x14, 0xb1, 0x96, 0xcc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TenvisClient is the client API for Tenvis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TenvisClient interface {
	Streaming(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (Tenvis_StreamingClient, error)
}

type tenvisClient struct {
	cc *grpc.ClientConn
}

func NewTenvisClient(cc *grpc.ClientConn) TenvisClient {
	return &tenvisClient{cc}
}

func (c *tenvisClient) Streaming(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (Tenvis_StreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tenvis_serviceDesc.Streams[0], "/network.Tenvis/Streaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &tenvisStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tenvis_StreamingClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type tenvisStreamingClient struct {
	grpc.ClientStream
}

func (x *tenvisStreamingClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TenvisServer is the server API for Tenvis service.
type TenvisServer interface {
	Streaming(*StreamingRequest, Tenvis_StreamingServer) error
}

func RegisterTenvisServer(s *grpc.Server, srv TenvisServer) {
	s.RegisterService(&_Tenvis_serviceDesc, srv)
}

func _Tenvis_Streaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TenvisServer).Streaming(m, &tenvisStreamingServer{stream})
}

type Tenvis_StreamingServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type tenvisStreamingServer struct {
	grpc.ServerStream
}

func (x *tenvisStreamingServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _Tenvis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.Tenvis",
	HandlerType: (*TenvisServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Streaming",
			Handler:       _Tenvis_Streaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tenvis.proto",
}
